/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package speakerverification_plp_svm;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author WiraIndra
 */

public class GUI extends javax.swing.JFrame {
    Recorder r = new Recorder();
    
    private static File audioFile;
    public GUI() {
        initComponents();       
        panelSample1.setVisible(false);
        panelSample2.setVisible(false);
        panelSample3.setVisible(false);
        panelSample4.setVisible(false);
        panelSample5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        speakerName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelSample1 = new javax.swing.JPanel();
        btnSample1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sample1 = new javax.swing.JTextField();
        panelSample2 = new javax.swing.JPanel();
        btnSample2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sample2 = new javax.swing.JTextField();
        panelSample3 = new javax.swing.JPanel();
        btnSample3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sample3 = new javax.swing.JTextField();
        panelSample4 = new javax.swing.JPanel();
        btnSample4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sample4 = new javax.swing.JTextField();
        panelSample5 = new javax.swing.JPanel();
        btnSample5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sample5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listData = new javax.swing.JList();
        loadDataButton = new javax.swing.JButton();
        audioText = new javax.swing.JTextField();
        plotPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Ucapkan kata 'BUKA' sebanyak  5 kali dengan range masing-masing 2 detik");

        jLabel9.setText("Nama:");

        speakerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakerNameActionPerformed(evt);
            }
        });

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSample1.setText("Take Sample 1");
        btnSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSample1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tersimpan:");

        sample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSample1Layout = new javax.swing.GroupLayout(panelSample1);
        panelSample1.setLayout(panelSample1Layout);
        panelSample1Layout.setHorizontalGroup(
            panelSample1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSample1)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sample1)
                .addContainerGap())
        );
        panelSample1Layout.setVerticalGroup(
            panelSample1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSample1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSample1)
                    .addComponent(jLabel4)
                    .addComponent(sample1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSample2.setText("Take Sample 2");
        btnSample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSample2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tersimpan:");

        sample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSample2Layout = new javax.swing.GroupLayout(panelSample2);
        panelSample2.setLayout(panelSample2Layout);
        panelSample2Layout.setHorizontalGroup(
            panelSample2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSample2)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sample2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSample2Layout.setVerticalGroup(
            panelSample2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSample2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSample2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSample2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(sample2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSample2))
                .addContainerGap())
        );

        btnSample3.setText("Take Sample 3");
        btnSample3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSample3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tersimpan:");

        sample3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSample3Layout = new javax.swing.GroupLayout(panelSample3);
        panelSample3.setLayout(panelSample3Layout);
        panelSample3Layout.setHorizontalGroup(
            panelSample3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSample3)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sample3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSample3Layout.setVerticalGroup(
            panelSample3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSample3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSample3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(sample3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSample3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSample4.setText("Take Sample 4");
        btnSample4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSample4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tersimpan:");

        sample4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSample4Layout = new javax.swing.GroupLayout(panelSample4);
        panelSample4.setLayout(panelSample4Layout);
        panelSample4Layout.setHorizontalGroup(
            panelSample4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSample4)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sample4)
                .addContainerGap())
        );
        panelSample4Layout.setVerticalGroup(
            panelSample4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSample4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSample4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(sample4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSample4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSample5.setText("Take Sample 5");
        btnSample5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSample5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tersimpan:");

        sample5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSample5Layout = new javax.swing.GroupLayout(panelSample5);
        panelSample5.setLayout(panelSample5Layout);
        panelSample5Layout.setHorizontalGroup(
            panelSample5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSample5)
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sample5)
                .addContainerGap())
        );
        panelSample5Layout.setVerticalGroup(
            panelSample5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSample5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSample5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSample5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(sample5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSample5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelSample1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speakerName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelSample2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSample3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSample4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSample5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(speakerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(panelSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSample2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSample3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSample4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSample5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Get Data Set", jPanel3);

        listData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listData);

        loadDataButton.setText("Load Data");
        loadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataButtonActionPerformed(evt);
            }
        });

        audioText.setText("Audio Data");

        javax.swing.GroupLayout plotPanelLayout = new javax.swing.GroupLayout(plotPanel);
        plotPanel.setLayout(plotPanelLayout);
        plotPanelLayout.setHorizontalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        plotPanelLayout.setVerticalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(audioText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDataButton)
                    .addComponent(audioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(plotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Data", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Testing", jPanel2);

        jLabel1.setText("Speaker Verification");

        jLabel2.setText("by wiraindrak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void speakerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speakerNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelSample1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSample1ActionPerformed
        String fileName = speakerName.getText()+"_1";
        //Recorder r = new Recorder();
        r.getAudio(fileName);
        sample1.setText(fileName);
        panelSample2.setVisible(true);
    }//GEN-LAST:event_btnSample1ActionPerformed

    private void sample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample1ActionPerformed

    private void btnSample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSample2ActionPerformed
        String fileName = speakerName.getText()+"_2";
//        Recorder r = new Recorder();
        r.getAudio(fileName);
        sample2.setText(fileName);
        panelSample3.setVisible(true);
    }//GEN-LAST:event_btnSample2ActionPerformed

    private void sample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample2ActionPerformed

    private void btnSample3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSample3ActionPerformed
        String fileName = speakerName.getText()+"_3";
//        Recorder r = new Recorder();
        r.getAudio(fileName);
        sample3.setText(fileName);
        panelSample4.setVisible(true);
    }//GEN-LAST:event_btnSample3ActionPerformed

    private void sample3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample3ActionPerformed

    private void btnSample4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSample4ActionPerformed
        String fileName = speakerName.getText()+"_4";
//        Recorder r = new Recorder();
        r.getAudio(fileName);
        sample4.setText(fileName);
        panelSample5.setVisible(true);
    }//GEN-LAST:event_btnSample4ActionPerformed

    private void sample4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample4ActionPerformed

    private void btnSample5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSample5ActionPerformed
        String fileName = speakerName.getText()+"_5";
//        Recorder r = new Recorder();
        r.getAudio(fileName);
        sample5.setText(fileName);
    }//GEN-LAST:event_btnSample5ActionPerformed

    private void sample5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample5ActionPerformed

    private void loadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataButtonActionPerformed
        DefaultListModel DLM = new DefaultListModel();

        File folder = new File("dataset/");
        File[] listOfFiles = folder.listFiles();

        for(int i=0; i<listOfFiles.length; i++){
            File file = listOfFiles[i];
            if(file.isFile() && file.getName().endsWith(".wav")){
                String conten = file.getName();
                DLM.addElement(conten);
            }
        }
        listData.setModel(DLM);
        
        listData.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt){
                JList list = (JList)evt.getSource();
                if (evt.getClickCount()==2){
                    int index = list.locationToIndex(evt.getPoint());
                    audioFile = listOfFiles[index];
                    audioText.setText(audioFile.getName());
                    AudioInputStream stream = null;
                    
                    Audio audio = new Audio(audioFile);
                    audio.getAudioData();
                    plotWave(audio.amplitudeData, "Audio Data", "Frequency", "Amplitudo");
                    
                    PLP plp = new PLP(audioFile);
//                    System.out.println("durasi : "+plp.durasi);
//                    System.out.println("jumlah frame : "+plp.jumlahFrame);
//                    System.out.println("panjang frame : "+plp.panjangFrame);
//                    System.out.println(Math.PI);
                    plp.runFFT();                    
                    
//                    plotWave(duaDimensiToSatuDimensi(plp.power), "Power Spectrum", "Frequency", "Power");
                    
                }
            }
        });
    }//GEN-LAST:event_loadDataButtonActionPerformed
    
    private void plotWave(Double[] data, String judul, String dataX, String dataY) {

        XYSeries soundWave = new XYSeries(data.length);

        for (int i = 0; i < data.length; ++i) {
            soundWave.add(i, data[i]);
        }
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(soundWave);
        
        JFreeChart chart = ChartFactory.createXYLineChart(judul, dataX, dataY, dataset);
        
        ChartPanel cp = new ChartPanel(chart);
        cp.setBounds(0, 0, plotPanel.getWidth(), plotPanel.getHeight());
        
        this.plotPanel.removeAll();
        plotPanel.add(cp);
        cp.updateUI();       
    }
    
    private Double[] duaDimensiToSatuDimensi(Double[][] data){
        Double[] x = new Double[data.length*data[0].length];
        int k = 0;
        for (int i = 0; i < data.length; i++) {
            for (int j = 0; j < data[i].length; j++) {
                x[k] = data[i][j];
                k++;
            }
        }
        return x;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField audioText;
    private javax.swing.JButton btnSample1;
    private javax.swing.JButton btnSample2;
    private javax.swing.JButton btnSample3;
    private javax.swing.JButton btnSample4;
    private javax.swing.JButton btnSample5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listData;
    private javax.swing.JButton loadDataButton;
    private javax.swing.JPanel panelSample1;
    private javax.swing.JPanel panelSample2;
    private javax.swing.JPanel panelSample3;
    private javax.swing.JPanel panelSample4;
    private javax.swing.JPanel panelSample5;
    private javax.swing.JPanel plotPanel;
    private javax.swing.JTextField sample1;
    private javax.swing.JTextField sample2;
    private javax.swing.JTextField sample3;
    private javax.swing.JTextField sample4;
    private javax.swing.JTextField sample5;
    private javax.swing.JTextField speakerName;
    // End of variables declaration//GEN-END:variables
}
